server:
  port: 8673
spring:
  mail:
    host: localhost
    port: 1025
    username: user
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  application:
    name: "message"
  cloud:
    function:
      definition: email|orderEmail
    stream:
      bindings:
        email-in-0:
          destination: send-communication
          group: ${spring.application.name}
        orderEmail-in-0:
          destination: send-orderDetails
          group: ${spring.application.name}
        email-out-0:
          destination: communication-sent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

