server:
  port: 8083

#spring.kafka.producer.bootstrap-server=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.properties.spring.json.type.mapping=paymentConfirmation:com.ecomm.payment.Notification.PaymentNotificationRequest
spring:
  cloud:
    config:
      enabled: false
    openfeign:
      circuitbreaker:
        enabled: true
    compatibility-verifier:
      enabled: false
  application:
    name: "payment-service"
  datasource:
    url: "jdbc:postgresql://localhost:5432/orders"
    username: "user"
    password: "password"
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      explousre: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
info:
  app:
    name: "Payment service"
    description: "Ecomm Payment microservice"
    version: "1.0.0"


