spring:
  application:
    name: order-service
#  config:
#    import: optional:configserver:http://localhost:8888
#  kafka:
#    producer:
#      bootstrap-server: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.jsonSerializer
#      properties:
#        spring.json.type.mapping: orderConfirmation:com.example.Order.producer.OrderConfirmation
