spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/customer"
    driver-class-name: "org.postgresql.Driver"
    username: "user"
    password: "password"

  jpa:
    hibernate:
      ddl-auto: "update"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    generate-ddl: true
server:
  port: 8080